"Flights" Dataset, exploratory analysis -- Miguel Martín González

In [3]:
#install.packages('nycflights13') ## If not already installed
library(nycflights13)

Warning message:
"package 'nycflights13' was built under R version 4.5.3"

In [4]:
 data('flights')
 head(flights , 5)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819
2 2013 1     1   533      529             4         850      830
3 2013 1     1   542      540             2         923      850
4 2013 1     1   544      545            -1        1004     1022
5 2013 1     1   554      600            -6         812      837
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00

In [9]:
nyflight = flights['year',][2013, ]

head(nyflight)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 NA   NA    NA  NA       NA             NA        NA       NA
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 NA        NA      NA     NA      NA     NA   NA       NA       NA   NA
  time_hour
1 <NA>